"""
VRPReporter: クラッシュ → VRPレポート自動生成 → メール通知
・Gmail SMTPでメール送信（Resend不要）
・CVSS 8.0以上は即時通知
・それ以外は日次サマリー
・VRPレポートのMarkdown草稿を自動生成
"""
import asyncio
import json
import logging
import smtplib
import sqlite3
import time
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

import aiohttp

from triage.minimizer import Minimizer, Bisector, PatchGenerator

log = logging.getLogger('reporter')


class VRPReporter:
    def __init__(self, config: dict):
        self.config    = config
        self.notify    = config['notification']
        self.triage    = config['triage']
        self.db_path   = config['infra']['db_path']
        self._daily_queue = []

    async def handle(self, crash: dict, analysis: dict):
        """クラッシュを受け取り、最小化→レポート生成→通知"""
        engine = crash.get('engine', 'v8')

        # 1. 最小化
        if self.triage.get('auto_minimize') and crash.get('js_code'):
            log.info(f"Minimizing {crash['id']}...")
            minimizer = Minimizer(self.config, engine)
            minimized = await asyncio.get_event_loop().run_in_executor(
                None, minimizer.minimize, crash['js_code']
            )
            crash['minimized_code'] = minimized
            self._save_minimized(crash['id'], minimized)

        # 2. Bisect
        bisect_commit = None
        if self.triage.get('auto_bisect'):
            log.info(f"Bisecting {crash['id']}...")
            bisector = Bisector(self.config, engine)
            bisect_commit = await bisector.bisect(crash)
            if bisect_commit:
                self._save_bisect(crash['id'], bisect_commit)
                crash['bisect_commit'] = bisect_commit

        # 3. パッチ案生成
        patch = None
        if self.triage.get('auto_patch'):
            log.info(f"Generating patch for {crash['id']}...")
            patcher = PatchGenerator(self.config)
            patch = await patcher.generate(crash, analysis)
            if patch:
                self._save_patch(crash['id'], patch)
                crash['patch'] = patch

        # 4. VRPレポート草稿生成
        report_md = self._generate_report(crash, analysis, bisect_commit, patch)
        self._save_report(crash['id'], report_md)

        # 5. 通知
        cvss = analysis.get('cvss', 0.0)
        threshold = self.notify['thresholds']['immediate']

        if cvss >= threshold:
            # 即時メール通知
            await self._send_immediate(crash, analysis, report_md)
        else:
            # 日次サマリーキューに追加
            self._daily_queue.append({
                'crash': crash,
                'analysis': analysis,
            })
            log.info(
                f"Queued for daily summary: {crash['id']} CVSS={cvss}"
            )

    def _generate_report(
        self, crash: dict, analysis: dict,
        bisect_commit: Optional[str], patch: Optional[str]
    ) -> str:
        """VRPレポートのMarkdown草稿を生成"""
        engine    = crash.get('engine', 'v8').upper()
        poc       = crash.get('minimized_code') or crash.get('js_code', '')
        now       = datetime.now(timezone.utc).strftime('%Y-%m-%d')
        target    = analysis.get('target_program', 'Google Chrome VRP')

        report = f"""# {analysis.get('report_title', 'Security Bug Report')}

## Summary

{analysis.get('attack_scenario', 'Memory corruption bug in {engine}.')}

## Affected Version

- Engine: {engine}
- Reported: {now}
- Component: {analysis.get('affected_component', 'Unknown')}

## Severity

- Type: {analysis.get('crash_type', 'Unknown')}
- CVSS: {analysis.get('cvss', 0.0)}
- Exploitability: {analysis.get('exploitability', 'unknown')}
- Estimated Reward: ${analysis.get('estimated_reward_min', 0):,} ~ ${analysis.get('estimated_reward_max', 0):,}

## Reproduction Steps

1. Build d8/jsc with ASAN:
   ```bash
   # V8
   tools/dev/gm.py x64.asan
   # JSC
   Tools/Scripts/build-webkit --jsc-only --debug
   ```

2. Run the PoC:
   ```bash
   ./d8 --allow-natives-syntax poc.js
   ```

## Proof of Concept

```javascript
{poc[:3000]}
```

## Crash Output

```
{crash.get('stderr', '')[:2000]}
```
"""

        if bisect_commit:
            report += f"""
## Bisection

Introducing commit: `{bisect_commit[:8] if bisect_commit else 'TBD'}`

```bash
git bisect start
git bisect bad HEAD
git bisect good {bisect_commit[:8] if bisect_commit else 'KNOWN_GOOD'}
# ... bisect steps
```
"""

        if patch:
            report += f"""
## Suggested Fix

{patch}
"""

        report += f"""
## Impact

This vulnerability could allow an attacker to:
{analysis.get('attack_scenario', 'Cause memory corruption in the JavaScript engine.')}

---
*Generated by v8fuzz automated security research system*
*Target: {target}*
"""
        return report

    async def _send_immediate(
        self, crash: dict, analysis: dict, report_md: str
    ):
        """即時メール通知（CRITICAL: CVSS 8.0以上）"""
        cvss    = analysis.get('cvss', 0.0)
        engine  = crash.get('engine', 'v8').upper()
        est_min = analysis.get('estimated_reward_min', 0)
        est_max = analysis.get('estimated_reward_max', 0)

        subject = (
            f"[CRITICAL] {crash['id']} {engine} "
            f"{analysis.get('crash_type','?')} CVSS{cvss}"
        )

        html = f"""
<div style="font-family: monospace; max-width: 600px;">
  <h2 style="color: #d73a49;">🔴 新規クラッシュ検出</h2>

  <table style="border-collapse: collapse; width: 100%;">
    <tr><td style="padding: 6px; color: #666;">ID</td>
        <td style="padding: 6px;"><b>{crash['id']}</b></td></tr>
    <tr><td style="padding: 6px; color: #666;">エンジン</td>
        <td style="padding: 6px;">{engine}</td></tr>
    <tr><td style="padding: 6px; color: #666;">種別</td>
        <td style="padding: 6px;">{analysis.get('crash_type','?')}</td></tr>
    <tr><td style="padding: 6px; color: #666;">CVSS</td>
        <td style="padding: 6px; color: #d73a49;"><b>{cvss}</b></td></tr>
    <tr><td style="padding: 6px; color: #666;">推定報奨金</td>
        <td style="padding: 6px; color: #28a745;">
          <b>${est_min:,} ~ ${est_max:,}</b></td></tr>
    <tr><td style="padding: 6px; color: #666;">最小化</td>
        <td style="padding: 6px;">
          {'✅ 完了' if crash.get('minimized_code') else '⏳ 処理中'}</td></tr>
    <tr><td style="padding: 6px; color: #666;">Bisect</td>
        <td style="padding: 6px;">
          {crash.get('bisect_commit','⏳ 処理中')}</td></tr>
  </table>

  <h3>最小化済みPoC</h3>
  <pre style="background: #f6f8fa; padding: 12px; border-radius: 6px;
              overflow-x: auto; font-size: 12px;">
{(crash.get('minimized_code') or crash.get('js_code',''))[:1000]}
  </pre>

  <p>
    <a href="{self.config['api']['worker_url']}/crashes/{crash['id']}"
       style="background: #d73a49; color: white; padding: 8px 16px;
              border-radius: 4px; text-decoration: none;">
      ダッシュボードで確認
    </a>
  </p>
</div>
"""

        await self._send_email(subject, html)
        log.info(f"Immediate notification sent: {crash['id']}")

    async def send_daily_summary(self):
        """日次サマリーメールを送信"""
        stats = self._get_daily_stats()
        queue = self._daily_queue.copy()
        self._daily_queue.clear()

        subject = (
            f"[DAILY] V8:{stats['v8_crashes']}件 / "
            f"JSC:{stats['jsc_crashes']}件 / "
            f"実行:{stats['total_execs']:,}回 / "
            f"API ${stats['api_spend']:.2f}"
        )

        crashes_html = ""
        for item in queue[:10]:  # 最大10件
            c = item['crash']
            a = item['analysis']
            crashes_html += f"""
<tr>
  <td style="padding: 6px;">{c['id']}</td>
  <td style="padding: 6px;">{c.get('engine','?').upper()}</td>
  <td style="padding: 6px;">{a.get('crash_type','?')}</td>
  <td style="padding: 6px; color: {'#d73a49' if a.get('cvss',0) >= 7 else '#856404'};">
    {a.get('cvss',0)}</td>
  <td style="padding: 6px; color: #28a745;">
    ${a.get('estimated_reward_min',0):,}~${a.get('estimated_reward_max',0):,}</td>
</tr>
"""

        html = f"""
<div style="font-family: monospace; max-width: 700px;">
  <h2>📊 デイリーレポート</h2>

  <table style="border-collapse: collapse; width: 100%;">
    <tr><td style="padding: 6px; color: #666;">V8 実行数</td>
        <td style="padding: 6px;">{stats['v8_execs']:,} 回</td></tr>
    <tr><td style="padding: 6px; color: #666;">JSC 実行数</td>
        <td style="padding: 6px;">{stats['jsc_execs']:,} 回</td></tr>
    <tr><td style="padding: 6px; color: #666;">V8 クラッシュ</td>
        <td style="padding: 6px;">{stats['v8_crashes']} 件</td></tr>
    <tr><td style="padding: 6px; color: #666;">JSC クラッシュ</td>
        <td style="padding: 6px;">{stats['jsc_crashes']} 件</td></tr>
    <tr><td style="padding: 6px; color: #666;">VRP候補</td>
        <td style="padding: 6px; color: #28a745;">
          <b>{stats['vrp_candidates']} 件</b></td></tr>
    <tr><td style="padding: 6px; color: #666;">API消費</td>
        <td style="padding: 6px;">${stats['api_spend']:.2f}</td></tr>
  </table>

  {f'''
  <h3>VRP候補 ({len(queue)}件)</h3>
  <table style="border-collapse: collapse; width: 100%;
                border: 1px solid #e1e4e8;">
    <tr style="background: #f6f8fa;">
      <th style="padding: 6px; text-align: left;">ID</th>
      <th style="padding: 6px; text-align: left;">Engine</th>
      <th style="padding: 6px; text-align: left;">Type</th>
      <th style="padding: 6px; text-align: left;">CVSS</th>
      <th style="padding: 6px; text-align: left;">推定報奨金</th>
    </tr>
    {crashes_html}
  </table>
  ''' if queue else '<p>本日のVRP候補: なし</p>'}

  <p>
    <a href="{self.config['api']['worker_url']}"
       style="background: #0366d6; color: white; padding: 8px 16px;
              border-radius: 4px; text-decoration: none;">
      ダッシュボードを開く
    </a>
  </p>
</div>
"""

        await self._send_email(subject, html)
        log.info("Daily summary sent")

    async def _send_email(self, subject: str, html: str):
        """Gmail SMTPでメール送信"""
        loop = asyncio.get_event_loop()
        await loop.run_in_executor(None, self._send_email_sync, subject, html)

    def _send_email_sync(self, subject: str, html: str):
        """Gmail SMTP同期送信"""
        gmail_user = self.notify['gmail_address']
        gmail_pass = self.notify['gmail_app_password']
        to_email   = self.notify['to_email']

        try:
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From']    = f"v8fuzz <{gmail_user}>"
            msg['To']      = to_email

            msg.attach(MIMEText(html, 'html'))

            with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
                server.login(gmail_user, gmail_pass)
                server.sendmail(gmail_user, to_email, msg.as_string())

            log.info(f"Email sent: {subject[:50]}")
        except Exception as e:
            log.error(f"Gmail send error: {e}")

    def _get_daily_stats(self) -> dict:
        """当日の統計を取得"""
        cutoff = time.time() - 86400
        with sqlite3.connect(self.db_path) as db:
            v8 = db.execute("""
                SELECT COUNT(*) FROM crashes
                WHERE engine='v8' AND timestamp > ?
            """, (cutoff,)).fetchone()[0]

            jsc = db.execute("""
                SELECT COUNT(*) FROM crashes
                WHERE engine='jsc' AND timestamp > ?
            """, (cutoff,)).fetchone()[0]

            vrp = db.execute("""
                SELECT COUNT(*) FROM crashes
                WHERE vrp_eligible=1 AND timestamp > ?
            """, (cutoff,)).fetchone()[0]

        return {
            'v8_crashes':     v8,
            'jsc_crashes':    jsc,
            'v8_execs':       0,   # runner.pyから取得予定
            'jsc_execs':      0,
            'total_execs':    0,
            'vrp_candidates': vrp,
            'api_spend':      0.0, # 実装予定
        }

    def _save_minimized(self, crash_id: str, code: str):
        with sqlite3.connect(self.db_path) as db:
            db.execute(
                "UPDATE crashes SET minimized_code=? WHERE id=?",
                (code, crash_id)
            )

    def _save_bisect(self, crash_id: str, commit: str):
        with sqlite3.connect(self.db_path) as db:
            db.execute(
                "UPDATE crashes SET bisect_commit=? WHERE id=?",
                (commit, crash_id)
            )

    def _save_patch(self, crash_id: str, patch: str):
        with sqlite3.connect(self.db_path) as db:
            db.execute(
                "UPDATE crashes SET patch_code=? WHERE id=?",
                (patch, crash_id)
            )

    def _save_report(self, crash_id: str, report: str):
        """レポートをファイルとして保存"""
        from pathlib import Path
        report_dir = Path(self.config['infra']['log_dir']) / 'reports'
        report_dir.mkdir(parents=True, exist_ok=True)
        (report_dir / f"{crash_id}.md").write_text(report)
